/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QyrCdenEg4Y
 */

import { useEffect, useState } from "react";


export default function Card({ id, img, title, clickHandler, setModalActive }) {



  return (
    <div
      className="max-w-2xl bg-[#362221] rounded-xl shadow-md overflow-hidden mx-auto p-4 " onClick={() => { clickHandler(id); setModalActive(true) }}>
      <img
        alt="Beverage"
        className="object-cover w-full h-64 rounded"
        height="400"
        src={img}
        style={{
          aspectRatio: "600/400",
          objectFit: "cover",
        }}
        width="500" />
      <div className="py-8">
        <h2
          className="block mt-1 text-lg font-bold leading-tight text-black dark:text-white">
          {title}
        </h2>
      </div>
    </div>
  );
}
