/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QyrCdenEg4Y
 */

import Image from "next/image";


export default function Card({ id, img, title, clickHandler, setModalActive }) {



  return (
    <div
      className=" cursor-pointer max-w-[350px] bg-[#362221] rounded-xl shadow-md overflow-hidden mx-auto " onClick={() => { clickHandler(id); setModalActive(true) }}>
      <Image
        alt="Beverage"
        className="object-cover w-full rounded"
        src={img}
        style={{
          aspectRatio: "1/1",
          objectFit: "cover",
        }}
        width={350}
        height={100}
      />
      <div className="p-4">
        <h2
          className="block mt-1 text-lg font-bold leading-tight text-[#ffa2a2]">
          {title}
        </h2>
      </div>
    </div>
  );
}
