/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XGI6em6ntS0
 */
'use client'
import { AccordionTrigger, AccordionContent, AccordionItem, Accordion } from "@/components/ui/accordion"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import Link from "next/link"
import Card from "./card";
import { useEffect, useState } from "react";
import { Modal } from "./modal"



export default function Search() {
  const [categories, setCategories] = useState([])
  const [glasses, setGlasses] = useState([])
  const [ingredients, setIngredients] = useState([])
  const [alcoholFilter, setAlcoholFilter] = useState([])

  const [activeFilters, setActiveFilters] = useState(["Cocktail"])

  const [results, setResults] = useState([])

  const [activeCardData, setActiveCardData] = useState({})
  const [modalActive, setModalActive] = useState(false)

  const clickHandler = (id) => {
    fetch('https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=' + id)
      .then((response) => response.json())
      .then((data) => setActiveCardData(...data.drinks))
      .catch((error) => console.error('Error:', error));

    console.log(activeCardData)
  }

  useEffect(() => {
    if (categories.length < 1) {
      fetch('https://www.thecocktaildb.com/api/json/v1/1/list.php?c=list')
        .then((response) => response.json())
        .then((data) => setCategories(data.drinks))
        .catch((error) => console.error('Error:', error));
    }
    if (glasses.length < 1) {
      fetch('https://www.thecocktaildb.com/api/json/v1/1/list.php?g=list')
        .then((response) => response.json())
        .then((data) => setGlasses(data.drinks))
        .catch((error) => console.error('Error:', error));
    }
    if (ingredients.length < 1) {
      fetch('https://www.thecocktaildb.com/api/json/v1/1/list.php?i=list')
        .then((response) => response.json())
        .then((data) => setIngredients(data.drinks))
        .catch((error) => console.error('Error:', error));

    }
    if (alcoholFilter.length < 1) {
      fetch('https://www.thecocktaildb.com/api/json/v1/1/list.php?a=list')
        .then((response) => response.json())
        .then((data) => setAlcoholFilter(data.drinks))
        .catch((error) => console.error('Error:', error));

    }

    fetch('https://www.thecocktaildb.com/api/json/v1/1/filter.php?c=' + activeFilters.join(' '))
      .then((response) => response.json())
      .then((data) => setResults(data.drinks))
      .catch((error) => console.error('Error:', error));
  }, [categories, glasses, ingredients, alcoholFilter, activeFilters])

  return (
    <>
      {modalActive && <Modal closeModal={() => {
        setModalActive(false);
        setActiveCardData({})
      }} data={activeCardData} />}
      <section
        className="px-4 flex gap-10 min-h-screen text-white">
        <div className="flex flex-col gap-4 items-start w-1/6 py-2">
          <div className="flex items-center w-full">
            <input className="mr-[-30px] px-4 w-full py-2 text-[#0C0909] placeholder-[#0C0909] rounded-lg outline-none" placeholder="Search..." />
            <button className="bg-[#F64740] text-white p-4 rounded-full">
              <svg
                className=" h-5 w-5"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <circle cx="11" cy="11" r="8" />
                <path d="m21 21-4.3-4.3" />
              </svg>
            </button>
          </div>
          <Accordion className="w-full" collapsible type="single">
            <AccordionItem value="categories">
              <AccordionTrigger className="text-base text-white">Categories</AccordionTrigger>
              <AccordionContent>
                <div className="grid gap-2">
                  {categories.map((item, index) => {
                    return (
                      <Label key={index} className="flex items-center gap-2 font-normal text-white">
                        <Checkbox id="category-cocktail" />
                        {item.strCategory}
                      </Label>
                    )
                  })}
                </div>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="ingredients">
              <AccordionTrigger className="text-base text-white">Ingredients</AccordionTrigger>
              <AccordionContent>
                <div className="grid gap-2">
                  {ingredients.map((item, index) => {
                    return (
                      <Label key={index} className="flex items-center gap-2 font-normal text-white">
                        <Checkbox id="category-cocktail" />
                        {item.strIngredient1}
                      </Label>
                    )
                  })}
                </div>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="Glasses">
              <AccordionTrigger className="text-base text-white">Glasses</AccordionTrigger>
              <AccordionContent>
                <div className="grid gap-2">
                  {glasses.map((item, index) => {
                    return (
                      <Label key={index} className="flex items-center gap-2 font-normal text-white">
                        <Checkbox id="category-cocktail" />
                        {item.strGlass}
                      </Label>
                    )
                  })}
                </div>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="Alcohol">
              <AccordionTrigger className="text-base text-white">Alcohol</AccordionTrigger>
              <AccordionContent>
                <div className="grid gap-2">
                  {alcoholFilter.map((item, index) => {
                    return (
                      <Label key={index} className="flex items-center gap-2 font-normal text-white">
                        <Checkbox id="category-cocktail" />
                        {item.strAlcoholic}
                      </Label>
                    )
                  })}
                </div>
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>
        <div className="mr-10  ml-auto">
          <div className="grid gap-6 md:gap-8">
            {!results.length && <h2 className="text-lg font-bold tracking-tight text-white">Use the filters to find what you are looking for!</h2>}

            {!results.length ?
              null
              :
              <div className="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                {results.map((item, index) => {
                  return (
                    <Card key={index} title={item.strDrink} img={item.strDrinkThumb} id={item.idDrink} clickHandler={clickHandler} setModalActive={setModalActive} />
                  )
                })}
              </div>
            }
          </div>
        </div>
      </section>
    </>
  );
}
