/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/XGI6em6ntS0
 */
'use client'
import Card from "./card";
import { useEffect, useState } from "react";
import { Modal } from "./modal"
import Filter from "./filter";



export default function Search() {

  const [activeFilters] = useState({category: 'Cocktail'})

  const [results, setResults] = useState([])

  const [activeCardData, setActiveCardData] = useState({})
  const [modalActive, setModalActive] = useState(false)

  const clickHandler = (id) => {
    fetch('https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=' + id)
      .then((response) => response.json())
      .then((data) => setActiveCardData(...data.drinks))
      .catch((error) => console.error('Error:', error));

    console.log(activeCardData)
  }

  useEffect(() => {
    fetch('https://www.thecocktaildb.com/api/json/v1/1/filter.php?c=' + activeFilters.category)
      .then((response) => response.json())
      .then((data) => setResults(data.drinks))
      .catch((error) => console.error('Error:', error));
  }, [activeFilters])

  return (
    <>
      {modalActive && <Modal closeModal={() => {
        setModalActive(false);
        setActiveCardData({})
      }} data={activeCardData} />}
      <section
        className="px-4 flex gap-10 min-h-screen text-white">
        <div className="flex flex-col gap-4 items-start w-1/6 py-2">
          <div className="flex items-center w-full">
            <input className="mr-[-30px] px-4 w-full py-2 text-[#0C0909] placeholder-[#0C0909] rounded-lg outline-none" placeholder="Search..." />
            <button className="bg-[#F64740] text-white p-4 rounded-full">
              <svg
                className=" h-5 w-5"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg"
              >
                <circle cx="11" cy="11" r="8" />
                <path d="m21 21-4.3-4.3" />
              </svg>
            </button>
          </div>
          <Filter />
        </div>
        <div className="mr-10  ml-auto">
          <div className="grid gap-6 md:gap-8">
            {!results.length && <h2 className="text-lg font-bold tracking-tight text-white">Use the filters to find what you are looking for!</h2>}
            {activeFilters.length &&
              <ol className="flex gap-4">
                {
                  activeFilters.map((item, index) => {
                    return (
                      <li key={index} className="bg-[#F64740] px-6 py-2 rounded-full">{item}</li>
                    )
                  })
                }
              </ol>
            }
            {!results.length ?
              null
              :
              <div className="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                {results.map((item, index) => {
                  return (
                    <Card key={index} title={item.strDrink} img={item.strDrinkThumb} id={item.idDrink} clickHandler={clickHandler} setModalActive={setModalActive} />
                  )
                })}
              </div>
            }
          </div>
        </div>
      </section>
    </>
  );
}
